name: JMeter Tests

on:
  workflow_dispatch:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          export PATH=$PATH:$PWD/apache-jmeter-5.6.3/bin

      - name: Run JMeter tests
        run: |
          jmeter -n -t JMeter/performance_test.jmx -l JMeter/test_results/results.csv -e -o reports/

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: JMeter/test_results/results.csv

      - name: Upload JMeter HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: reports/