name: JMeter Tests

on:
  workflow_dispatch:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest
    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create reports directory
        run: mkdir -p JMeter/test_results/reports

      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for OWASP Juice Shop to start..."
          for i in {1..20}; do
            if curl -s http://localhost:3000 | grep -q '<title>OWASP Juice Shop</title>'; then
              echo "Juice Shop is ready!"
              exit 0
            fi
            echo "Still waiting for Juice Shop..."
            sleep 5
          done
          echo "Juice Shop failed to start in time."
          exit 1

      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: JMeter/performance_test.jmx
          args: "-l JMeter/test_results/results.csv -e -o JMeter/test_results/reports/"

      - name: List full test results directory
        run: find JMeter/test_results/ -type f

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: JMeter/test_results/results.csv
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: JMeter/test_results/reports
          if-no-files-found: error
