name: JMeter Tests

on:
  workflow_dispatch:

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create reports directory
        run: mkdir -p JMeter/test_results/reports

      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: JMeter/performance_test.jmx
          args: "-n -t JMeter/performance_test.jmx -l JMeter/test_results/results.csv -e -o JMeter/test_results/reports/"

      - name: List full test results directory
        run: find JMeter/test_results/ -type f

      - name: Upload JMeter results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: JMeter/test_results/results.csv
          if-no-files-found: error

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: JMeter/test_results/reports
          if-no-files-found: error
