name: Postman Tests

on:
  workflow_dispatch:

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    services:
      juice-shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Wait for Juice Shop to be ready
        run: |
          echo "Waiting for OWASP Juice Shop to start..."
          for i in {1..20}; do
            if curl -s http://localhost:3000 | grep -q '<title>OWASP Juice Shop</title>'; then
              echo "Juice Shop is ready!"
              exit 0
            fi
            echo "Still waiting for Juice Shop..."
            sleep 5
          done
          echo "Juice Shop failed to start in time."
          exit 1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman tests and generate HTML report
        run: |
          newman run Postman/juice-shop-collection.json \
            --environment MultiTool_Testing/Postman/postman-env.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman-report.html \
            --insecure

      - name: Upload HTML Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: postman-html-report
          path: newman-report.html
